class Constants:
    MPS: str = "mps"
    CPU: str = "cpu"
    CUDA: str = "cuda"
    STEP: str = "step"
    AMOUNT: str = "amount"
    IS_FRAUD: str = "isFraud"
    TRANSACTION_TYPE: str = "type"
    TYPE_ENCODED: str = "type_encoded"
    AMOUNT_NORMALIZED: str = "amount_normalized"
    NEW_RECIPIENT_BALANCE: str = "newbalanceDest"
    NEW_TRANSACTION_BALANCE: str = "newbalanceOrig"
    BEFORE_TRANSACTION_BALANCE: str = "oldbalanceOrg"
    RECIPIENT_CUSTOMER_ACCOUNT_NAME: str = "nameDest"
    INITIAL_RECIPIENT_BALANCE: str = "oldbalanceDest"
    INITIATING_CUSTOMER_ACCOUNT_NAME: str = "nameOrig"
    NEW_BALANCE_ORIGIN_NORMALIZED: str = "new_balance_origin_normalized"
    NEW_BALANCE_DESTINATION_NORMALIZED: str = "new_balance_destination_normalized"
